### ISSUE TITLE
P.152: model.fit() の引数がソースと紙面で異なる

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#10]
**ページ数**

P.152 の真ん中のテキストボックス

**内容**

誤：history = model.fit(x, y, batch_size=BATCH_SIZE, epochs=EPOCHS)
正：history = model.fit(x, y, batch_size=BATCH_SIZE, epochs=EPOCHS, callbacks=[print_callback])

**コメント**

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。

@KazumaAndoh さん
こちらも誤記訂正必要と思います。

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
