### ISSUE TITLE
P.155: 「diversity = 1.0」の時だけ「char_numb = 100」が明記されている

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#11]
**ページ数**

P.155 のテキストボックス内の 2 段落目

**内容**

誤：char_numb = 100 diversity = 1.0
正：diversity = 1.0

**コメント**

ここだけ書き方が違うのは不自然に感じたので、報告させて頂きます。

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。

@KazumaAndoh さん
特に問題はない内容ですが、指摘の通り不自然ではあります。次回直すタイミングあるなら、一緒に直した方が良いかなとは思います。

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
