### ISSUE TITLE
P.161: ソースに無いコードが記載されている

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#12]
**ページ数**

P.161 の 1 行目（テキストボックス内）

**内容**

誤：text = normalize_text(text)
正：（削除）

**コメント**

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。

@KazumaAndoh さん
ないのが正しいので、正誤表追加が良いかと思います。

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
