### ISSUE TITLE
P.162: open('analysis_text.txt') の encoding が shift_jis になっている

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#13]
**ページ数**

P.162 の 2 つめのテキストボックス内の 2 行目

**内容**

誤：encoding='shift_jis'
正：encoding='utf-8'

**コメント**

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。

@KazumaAndoh さん
こちらも指摘の通りですので、正誤表に追加と思います。

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
