### ISSUE TITLE
P.186-187: モデルの変数名が代入時と参照時で異なる

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#14]
**ページ数**

- P.186 の最下行
- P.187 の 1 つ目のテキストボックスの 3 行目

**内容**

- P.186 の最下行
誤：model.eval()
正：model_mask.eval()

- P.187 の 1 つ目のテキストボックスの 3 行目
誤：outputs = model(tokens_tensor)
正：outputs = model_mask(tokens_tensor)

**コメント**

同様の誤りであったため、１件の Issue とさせて頂きました。

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。

@KazumaAndoh さん
指摘の通り、正誤表に追加が良いと思います。

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
