### ISSUE TITLE
P.92 画像名が紙面とソースで異なる

### ISSUE THREAD

**Issue by koichirokato** [karaage0703/karaage-ai-book#15]
**ページ数**

P.92 真ん中あたり

**内容**

P.92の真ん中あたりの画像の画像名が
「ki_concat.jpg」になっています。(choki_concat.jpgのミス？)
ソースでは「concat.jpg」で保存されます。

**コメント**

重ね重ねあまり主旨とは関係ないところですみません。

P.92の上の方の画像も「choki.jpg」となっていてその画像は存在しない(choki_01.jpgは存在する)ので
ファイル名はあまり関係ないと思いますが、、
よろしければご確認お願いします。

**Comment by karaage0703** [comment]
@koichirokato さん
ご指摘ありがとうございます。確かに不自然ですね。

@KazumaAndoh さん
「ki_concat.jpg」は、名前として不自然なため、正誤表追記が良いかと思います。

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
