### ISSUE TITLE
P.298: MNIST モデルの変数名が後段のコードと異なる

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#17]
**ページ数**

P.298 下から 2 つめのテキストボックス

**内容**

誤：keras_model = ... 
正：keras_mnist_model = ...  

**コメント**

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
