### ISSUE TITLE
P.73: Google Colab 上でカメラを扱うためのプログラムのダウンロード URL

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#2]
**ページ数**

P.73 の下のほう

**内容**

プログラムのダウンロードコマンド（URL）に誤りがある。

誤：!wget https://raw.githubusercontent.com/karaage0703/karaage-ai-book/util/colab_camera.py
正：!wget https://raw.githubusercontent.com/karaage0703/karaage-ai-book/master/util/colab_camera.py

**コメント**

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。確認しましたが、ご指摘の通りでした。出版社の確認も必要なため、正誤表への反映は少々お待ちください。

@KazumaAndoh さん
すみません、こちら誤記でした。正誤表に反映必要と思います。

**Comment by KazumaAndoh** [comment]
@karaage0703 さん
了解です。正誤表への反映をお願いします。

@renkin3q さん
ご指摘をありがとうございました！

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に反映したので、こちらのissueはcloseします。

**Comment by renkin3q** [comment]
@karaage0703 さん
@KazumaAndoh さん
承知しました。ご対応頂きありがとうございました。
