### ISSUE TITLE
P.246, P.255 紙面：tostring()、ノートブックのソースコード：tobytes()

### ISSUE THREAD

**Issue by koichirokato** [karaage0703/karaage-ai-book#20]
**ページ数**

P.246, P.255ともに、 ソースコード部分

**内容**

該当ソースコード下部の、`img_str=`の部分

紙面
```
#encode to string
...
img_str = encimg.tostring()
...
```

[ノートブック](https://colab.research.google.com/drive/1dtBgF774jFSc405ik4C1Em0KM8IYUvTX?usp=sharing)
```
#encode to string
...
img_str = encimg.tobytes()
...
```

**コメント**

紙面のように`tostring`で実行したところ、実行はできたのですが、以下のWarningが出ました。
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.

**Comment by koichirokato** [comment]
すみません、このIssueですが、
#4 と内容が重複していました。
確認できておらず申し訳ありません。

**Comment by karaage0703** [comment]
@koichirokato さん
コメントありがとうございます。 #4 と重複していますので、こちらはcloseさせていただきますね。
