### ISSUE TITLE
P.204 紙面とソースで引数の値が異なる

### ISSUE THREAD

**Issue by koichirokato** [karaage0703/karaage-ai-book#21]
**ページ数**

P.204 一番上のテキストボックス

**内容**

紙面
```
plt.imshow((test_image[0] +1)/2) 
```

[ソース(ノートブック)](https://colab.research.google.com/drive/1d3HMpKMnVsaligeJAEeN9BV7uEbV5QRJ?usp=sharing)
```
plt.imshow((test_image[0] * 127.5 + 127.5) / 255)
```

**コメント**
ソースの方の引数内の分母分子の数字を127.5で割れば紙面の方になるので結果は変わらないのですが、
一応ご確認よろしくお願いします。

**Comment by karaage0703** [comment]
@koichirokato さん
コメントありがとうございます。紙面にコードを統一いたします。
