### ISSUE TITLE
p45 import split_train_val について

### ISSUE THREAD

**Issue by Ryoryoryo-create** [karaage0703/karaage-ai-book#23]
**ページ数**

ｐ45

import split_train_val
split_train_val.image_dir_train_val_split(
    dataset_original_dir, dataset_root_dir, train_size=0.67)

**内容**

実行すると、以下のエラーが発生しました。
https://colab.research.google.com/drive/13kLjdoz23fQIRT_zYR196pSxFEPHOS2k?usp=sharing#scrollTo=U17652B6BMbY
上記からコードをコピペをしても、同じ状況でした。

  File "/content/split_train_val.py", line 1
    <!DOCTYPE html><html lang="en"  data-adblockkey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANnylWw2vLY4hUn9w06zQKbhKBfvjFUCsdFlb6TdQhxb9RXWXuI4t31c+o8fYOv/s8q1LGPga3DE1L/tHU4LENMCAwEAAQ==_hTbiy7ntCSj8qk2PhHJF491kdRqD+2Gnl6pN/XjaBXc76RzmfkicLyp+tXmO3OY+gc7r6llJXu6k5liSplt8rw==><head><meta charset="utf-8"><title>githubsercontent.com&nbsp;-&nbspThis website is for sale!&nbsp;-&nbspgithubsercontent Resources and Information.</title><meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0"><meta name="description" content="This website is for sale! githubsercontent.com is your first and best source for all of the information you’re looking for. From general topics to more of what you would expect to find here, githubsercontent.com has it all. We hope you find what you are searching for!"><link
    ^
SyntaxError: invalid syntax

**コメント**

何卒、ご教示のほど、宜しくお願いいたします。

**Comment by karaage0703** [comment]
@Ryoryoryo-create さん
質問ありがとうございます。こちらで試してみましたが問題なく実行できました。
エラーメッセージからすると、`split_train_val.py`スクリプトがGoogle Colabに正しくダウンロードできていないように思えます。

一度、サポートサイトのGoogle Colabのノートブックを開いて、「ファイル」 -> 「ドライブにコピーを保存」を実行して、コピーしてから順に実行していただけないでしょうか？
正しく動くことが確認できるのではないかと思います。その後、何かスペルミスが無いか、一つずつ確認いただけましたら幸いです。

**Comment by Ryoryoryo-create** [comment]
karaage0703さん

ご返信、大変ありがとうございます。
お時間を頂戴してしまい、申し訳ありません。

追伸
ブログ、いつも楽しく拝見しています。

**Comment by karaage0703** [comment]
いえ、つまずきやすいところが分かり参考になりますので全く問題ありません。
問題解決しないようでしたら、また再度issueをReopenください。
