### ISSUE TITLE
colab_camera.py のインポートに関して

### ISSUE THREAD

**Issue by oto0216** [karaage0703/karaage-ai-book#24]
**ページ数**

P.74 上のほう

**内容**
colab_cameraのインポート時にエラーが発生します。

実行したコード：

import colab_camera

エラー内容：

  File "/content/colab_camera.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**コメント**
解決方法を教えていただけると助かります。
よろしくお願いいたします。

**Comment by oto0216** [comment]
度々すみません。
無事に解決しました！

自分の内容を見返してみたところ、colab_camera.pyが二つ出来てしまっているようでした。
最初に間違ったURLからダウンロードしてしまい、改めてダウンロードしなおした感じです。

なので、新しいノートブックを作成して改めて最初からやり直したら無事インポートできました。

お騒がせして申し訳ありませんでした。

一応、下記が失敗した実行結果になります。
##########
--2021-02-16 11:16:16--  https://github.com/karaage0703/karaage-ai-book/blob/master/util/colab_camera.py
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘colab_camera.py’

colab_camera.py         [ <=>                ] 114.06K  --.-KB/s    in 0.04s   

2021-02-16 11:16:16 (2.83 MB/s) - ‘colab_camera.py’ saved [116796]

##########
--2021-02-16 11:26:38--  https://raw.githubusercontent.com/karaage0703/karaage-ai-book/master/util/colab_camera.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3036 (3.0K) [text/plain]
Saving to: ‘colab_camera.py.1’

colab_camera.py.1   100%[===================>]   2.96K  --.-KB/s    in 0s      

2021-02-16 11:26:38 (40.6 MB/s) - ‘colab_camera.py.1’ saved [3036/3036]

##########

**Comment by karaage0703** [comment]
@oto0216 さん
無事解決できたようで良かったです。
クローズさせていただきます。
