### ISSUE TITLE
PoseEstimatorクラスの表記について

### ISSUE THREAD

**Issue by kskkoba** [karaage0703/karaage-ai-book#25]
**ページ数**

P.250の下1/3のあたり

**内容**

ex:  
誤：骨格を描画しているのは「estimator.py」の「PoseEstimator」というクラス  
正：骨格を描画しているのは「estimator.py」の「TfPoseEstimator」というクラス  

**コメント**
楽しく読ませていただきました。より良いものとなるよう貢献できればと思って投稿させていただきました。
サポートサイトからダウンロードさせていただいたestimator.pyの中を確認したところ、draw_humansのメソッドはTfPoseEstimatorの中にあったのでこちらが正しいのかと思い投稿させていただきました。もし私の投稿が誤っていたらご容赦ください。

**Comment by karaage0703** [comment]
@kskkoba さん
ご指摘ありがとうございます。指摘内容の通りです、誤記としてERRATA.mdに追記させていただきましたので本issueはCloseさせていただきます。
