### ISSUE TITLE
P40の教師データがダウンロード出来ないです。

### ISSUE THREAD

**Issue by Oryzae-O** [karaage0703/karaage-ai-book#27]
**ページ数**

ex: P.10 真ん中あたり

**内容**

ex:  xxxが分かりません・xxxについて教えてください

**コメント**

その他何かあれば（なければ空欄でOKです）
![2021-04-14(1)](https://user-images.githubusercontent.com/82478436/114630819-5496f800-9cf6-11eb-95aa-a871a6346631.png)

**Comment by karaage0703** [comment]
@Oryzae-O さん
スペルミスに見えます。
get でなく git になります。取り急ぎ。
