### ISSUE TITLE
データを分割するときのエラーの解決方法がわかりません

### ISSUE THREAD

**Issue by rock-oj** [karaage0703/karaage-ai-book#28]
**ページ数**

ex: P.46 最上段

**内容**

split_train_val.image_dir_train_val_split(
  dataset_original_dir, dataset_root_dir, train_size=0.67)

を実行すると下記のようなエラーとなります。

target_datasetsis already created.
target_datasets/trainis already created.
target_datasets/valis already created.
target_datasets/train/.gitis already created.
target_datasets/val/.gitis already created.
target_datasets/train/guis already created.
target_datasets/val/guis already created.
target_datasets/train/chokiis already created.
target_datasets/val/chokiis already created.
target_datasets/train/pais already created.
target_datasets/val/pais already created.
---------------------------------------------------------------------------
IsADirectoryError                         Traceback (most recent call last)
<ipython-input-43-bac4e81536f2> in <module>()
      1 split_train_val.image_dir_train_val_split(
----> 2   dataset_original_dir, dataset_root_dir, train_size=0.67)

1 frames
/usr/lib/python3.7/shutil.py in copyfile(src, dst, follow_symlinks)
    118         os.symlink(os.readlink(src), dst)
    119     else:
--> 120         with open(src, 'rb') as fsrc:
    121             with open(dst, 'wb') as fdst:
    122                 copyfileobj(fsrc, fdst)

IsADirectoryError: [Errno 21] Is a directory: 'datasets/.git/info'

**コメント**
「datasets/.git/info」はディレクトリであってファイルじゃないから開けないと言われているのは
わかるのですが、解決方法がよくわかりません。
ご教授いただけますと助かります。

**Comment by karaage0703** [comment]
@rock-oj さん
質問ありがとうございます。

P.40でgit cloneした後の2行目 `!rm -rf datasets/.git`が正しく実行できていない可能性がありそうです。
これが正しく実行できていれば `datasets/.git` 以下の不要なファイルは無くなるので、上記のエラーは出ないはずです。

一度、Google Colaboratoryの「ランタイム」 -> 「ランタイムを出荷時設定にリセット」を選択して、初期状態にしてから最初からやり直するのが良いかもしれません。

また、以下動画で実践方法を解説していますので、よろしければこちらも参考にしてみてください。
https://www.youtube.com/watch?v=-0zQjI6IiwI

**Comment by rock-oj** [comment]
無事、エラーが出なくなりました！
検討違いのところを中心に見てしまっていたので、質問してよかったです。

ありがとうございました！
