### ISSUE TITLE
P49にてラベルファイルが正しく作成されません。。。

### ISSUE THREAD

**Issue by fujinawa0003** [karaage0703/karaage-ai-book#29]
内容
*P49　!cat ./model/labels.txt
を実行後
pa
しか表示されません。
コードを見直しても同じように作製できているようにみえます。
どのような部分に不具合があると考えられますでしょうか？
お手数をおかけしますが宜しくお願いします。

**コメント**

**Comment by karaage0703** [comment]
@fujinawa0003 さん
質問ありがとうございます。

まずは、以下の画像分類のGoogle Colabノートブックをそのまま動かして、正しく動かすことを確認してみるのが良いかと思います。
https://colab.research.google.com/drive/13kLjdoz23fQIRT_zYR196pSxFEPHOS2k?usp=sharing

正しく動くコードを確認した上で、自分のコードと1行ずつ比べてみると良いかと思います。

ノートブックの実行方法は、以下の動画でも解説していますので、よろしければ参考にしてみてください。
https://www.youtube.com/watch?v=-0zQjI6IiwI&t=4s

**Comment by fujinawa0003** [comment]
@karaage0703 さん
さっそくのご回答ありがとうございます。
ご提案いただいた方法でコラボノートブックが起動することを確認し、
本に記載されていた下記のコードを実行後にラベルの中身を確認したところ、
paしか表示されないことがわかりました。
f = open(backup_dir + '/labels.txt','w')
f.write(label + '\n')
f.close()

理由はわからないのですが、前述のコードを削除して進めたいと思います。
ありがとうございました。
