### ISSUE TITLE
P.76: use_cam() が NameError になる

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#3]
**ページ数**

P.76 の真ん中から少し上

**内容**

誤：use_cam()
正：colab_camera.use_cam()

"colab_camera." が無いと次のエラーになる。
`NameError: name 'use_cam' is not defined`

**コメント**

もし意図的に省略していましたら、この Issue はリジェクトしてください。

**Comment by karaage0703** [comment]
@renkin3q さん
重ねがさね貴重なご指摘ありがとうございます。意図したものではありません。修正すべき点です。

@KazumaAndoh さん
Google Colab ノートブックの修正が反映もれていたようです。修正すべき点です。正誤表追加でよいでしょうか？
P256にも同様の箇所ありますが、こちらは正しく記載されていました。

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
