### ISSUE TITLE
p146 RMSprop のインポートエラー

### ISSUE THREAD

**Issue by aoronesy** [karaage0703/karaage-ai-book#31]
**ページ数**
p146の前半　ライブラリのインポート

**内容**
エラーなどは出ていなかったので問題ないかとは思うのですが
TensorFlow 2.6.0 だと```RMSprop```がインポートエラーとなりました。
[こちら](https://stackoverflow.com/questions/64844140/importerror-cannot-import-name-rmsprop-from-keras-optimizers)のstackoverflowを参考に

```from keras.optimizers import RMSprop``` から
```from tensorflow.keras.optimizers import RMSprop```
と変更したのですが、特に問題はなかったでしょうか？

**コメント**
Verを2.3.0に合わせていないのでこのようなことになるかとは思うので大変恐縮な質問で申し訳ないです。。。

**Comment by karaage0703** [comment]
@aoronesy さん
ご指摘ありがとうございます。バージョンアップにともなうエラーです。
対応は問題ありません。

正誤表、サポートサイトのコードを修正させていただきます。貴重なご意見ありがとうございました。
