### ISSUE TITLE
エラーで進めなくなりました

### ISSUE THREAD

**Issue by japython** [karaage0703/karaage-ai-book#32]
**ページ数**
P45

**内容**
下記表示が出たので分割ソフトはセーブされたと思われます。
2021-11-23 03:02:32 (109 MB/s) - ‘split_train_val.py’ saved [1529]

最下段のインポート文を入れるとスクリプト自体に何かあるといったエラー表示が出て進めなくなりました。
import split_train_val
split_train_val.image_dir_train_val_split(dataset_orignal_dir, dataset_root_dir, train_size=0.67)

 File "/content/split_train_val.py", line 1
    <!doctype html><html lang="en" data-adblockkey="MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANDrp2lz7AOmADaN8tA50LsWcjLFyQFcb/P2Txc58oYOeILb3vBw7J6f4pamkAQVSQuqYsKx3YzdUHCvbVZvFUsCAwEAAQ==_AtHpdUhIPNRad1+MQA+rt9NfP1Sg/50Td0BT4A+RxLmq5MyoD+vI/CVBlWsAtbG0SzkYA0FTA+u6Y0q9bwXULw=="><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/><link rel="preconnect" href="https://www.google.com" crossorigin><link rel="dns-prefetch" href="https://parking.bodiscdn.com" crossorigin><link rel="dns-prefetch" href="https://fonts.googleapis.com" crossorigin></head><body><div id="target" style='opacity: 0'></div><script>window.park = "eyJ1dWlkIjoiZTM4MzliNjEtMWZjMy1jMWJmLTBmYWEtMDg2YjVkNjk5YzM5IiwicGFnZV90aW1lIjoxNjM3NjM2NTUyLCJwYWdlX3VybCI6Imh0dHA6XC9cL3d3MjUucmF3LmdpdGh1YnNlcmNvbnRlbnQuY29tXC9rYXJhYWdlMDcwM1wva2FyYWFnZS1haS1ib29rXC9tYXN0ZXJcL3V0aWxcL3NwbGl0X3RyYWluX3ZhbC5weT9zdWJpZDE9MjAyMTExMjMtMTQwMi0zMWI1LTkwMzYtZGFlMDA4Njk4YjhiIiwicGFnZV9tZXRob2QiOiJHRVQiLCJwYWdlX3JlcXVlc3QiOnsic3ViaWQxIjoiMjAyMTExMjMtMTQwMi0zMWI1LTkwMzYtZGFlMDA4Njk4YjhiIn0sInBhZ2VfaGVhZGVycyI6eyJjb25uZWN0aW9uIjpbIktlZXAtQWxpdmUiXSwiaG9zdCI6WyJ3dzI1LnJhdy5naXRodWJzZXJjb250ZW50LmNvbSJdLCJhY2NlcHQtZW5jb2RpbmciOlsiaWRlbnRpdHkiXSwiYWNjZXB0IjpbIipcLyoiXSwidXNlci1hZ2VudCI6WyJXZ2V0XC8xLjE5LjQgKGxpbnV4LWdudSkiXX0sImhvc3QiOiJ3dzI1LnJhdy5naXRodWJzZXJjb250ZW50LmNvbSIsImlwIjoiMzQuMTQwLjE2NS4xNjkifQ==";</script><script src="/js...
    ^
SyntaxError: invalid syntax

**コメント**
特記事項なし

**Comment by japython** [comment]
失礼いたしました。
前回問い合わせの方同様、ダウンロードが不完全だったようで再ダウンロードしたら解決しました。

**Comment by karaage0703** [comment]
@japython 
解決したようでよかったです。反応遅くなりすみませんでした。
