### ISSUE TITLE
読み取り画像が回転してしまっている

### ISSUE THREAD

**Issue by ghost** [karaage0703/karaage-ai-book#33]
**ページ数**
P56でジャンケンから自分の画像に置き換えた

**内容**
P42に従って、画像を自分で用意した人物に置き換えて学習させました。
その際に、取り込んだデータが回転してしまっているのがありました。
何か原因などあるのでしょうか？

**コメント**
この質問を書き込むにあたりGitHubを初めて使いました。
登録に際して、「先生」か「学生」を選ぶ画面が出ましたが、
「学生」を選んでしまいました。
インターネットで記事を見ると、その他の職業も出ていましたが、
自分が登録する際は上記２つしか選択肢がありませんでした。
どうするのが正しいのかご存じでしたらアドバイスをいただけると幸いです。

**Comment by JackWilliamsThe3rd** [comment]
早速のご返信ありがとうございます。

いただいた情報をもとに試してみようと思います！

GitHubの登録もちょっと気になるので、一旦アカウントを削除して、
再度登録して確認してみようと思います！！
（返信できなくなってしまうと困るので、取り急ぎ簡単ですがお礼の連絡です。）
