### ISSUE TITLE
tf.keras.models.load_model('efficientnet_model.h5')のエラー

### ISSUE THREAD

**Issue by Bravoastro** [karaage0703/karaage-ai-book#34]
efficient_modelのh5ファイルを読み込ます時に、NameErrorの'tf' is not defined　が表示された。
また、ipynbファイルに参考としてissues26835が記載されているがこの意味も分かりません。
以下は、ipynbファイルの実行時の画面キャプチャーです。
![image](https://user-images.githubusercontent.com/72477868/155982095-68dc10c5-057e-4813-b914-dea316225d59.png)

**Comment by karaage0703** [comment]
質問ありがとうございます。書籍のページ数等を教えていただけると助かりますが、以下のノートブックに対する質問でしょうか？

[02_karaage_ai_book_image_classification_on_camera_2.ipynb](https://colab.research.google.com/drive/1St8V0KmbhBHzHtTRltoR4tFNi3e1VR9o?usp=sharing)

試しに実行してみましたが、特に問題なく読み込めました。

<img width="831" alt="image" src="https://user-images.githubusercontent.com/5562157/155991303-21f72f68-e9ca-4aa3-8fef-e4670ff365b7.png">

エラーから想像すると、最初の方のコードを実行していないように思えます。書籍を読みながら実行いただいていますでしょうか？本リポジトリは、書籍のサポートサイトとなっております。

**Comment by Bravoastro** [comment]
karaage様
お早うございます。
書籍は、kindel本でP95あたりだと思います。
申し訳ありません。エラーが表示されたipynbファイルを実行しましたが、問題なく実行できました。
昨日は何回も実行したのですが、エラーが出ていました。
GitHubはどうすればよいのでしょうか?
また、カメラの背景で結果が異なるように思いました。
これは、データ水増しでも同じ結果のように思いました。
背景に影響されなくするには、Albumentationでもっと多数のデータ水増しをすればよいのでしょうか?
（問題が出てきたら、また質問させていただいてもOKでしょうか?）
私は、年金生活者で趣味で出来合いの3次元姿勢推定SOFTをgoogle colabで動かしています。
まだ自分で、学習させたことはありませんが、将来やってみたいと思っています。
この時の制約は12時間縛りだと思っています。
カラアゲさんも色々書かれているので参考にさせていただきます。

2022年2月28日(月) 22:33 karaage ***@***.***>:

**Comment by karaage0703** [comment]
問題なく実行できたようでよかったです。

AIモデルの性能を上げる方法に関しては、基本的には書籍の通りですが、書籍ではあまり触れていないこととして、実際に認識させたい背景のデータを取得できるなら、教師データをテスト環境に近い状態で取得して増やすのが、実用上は効果あると思います。

年金で生活されているのですね。趣味で学習し続ける姿勢、素晴らしいです。頭が下がります。

本件は、解決したとのことで一旦closeしますが、何かありましたら私で答えられる範囲でしたら答えますので、いつでも質問していただいて問題ありません。
