### ISSUE TITLE
pytorchによるimage_classificationのipynbファイルの実行時のエラー

### ISSUE THREAD

**Issue by Bravoastro** [karaage0703/karaage-ai-book#35]
p70あたり
**内容**
tensorflow版の画像分類は問題なく出来ましたが、pytorch版では次のatrributeErrorが出て先に進めませんでした。
![image](https://user-images.githubusercontent.com/72477868/155990651-48a4bbc0-dbc8-4f58-9e1b-55c74bbd8987.png)

**Comment by karaage0703** [comment]
@Bravoastro 
ご指摘ありがとうございます。誤記でした。申し訳ありません。`sprit -> split`とする必要があります。

誤：
```python
split_train_val.image_dir_train_val_sprit(dataset_original_dir, dataset_root_dir, train_size=0.66)
```

正：
```python
split_train_val.image_dir_train_val_split(dataset_original_dir, dataset_root_dir, train_size=0.66)
```

コード修正いたしました。

**Comment by Bravoastro** [comment]
ありがとうございます。

2022年2月28日(月) 22:55 karaage ***@***.***>:
