### ISSUE TITLE
%tensorflow_version 1.x　でエラー

### ISSUE THREAD

**Issue by zugink** [karaage0703/karaage-ai-book#36]
**ページ数**

ex: P.242 最後

**内容**

%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)

でエラーが出ます。Tensorflow 1 is unsupported in Colab. と出ます。是非動かしてみたいので解決策を教えてください。

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-4-5e33bdecc50e>](https://localhost:8080/#) in <module>()
----> 1 get_ipython().magic('tensorflow_version 1.x')
      2 import tensorflow as tf
      3 print(tf.__version__)

2 frames
[/usr/local/lib/python3.7/dist-packages/google/colab/_tensorflow_magics.py](https://localhost:8080/#) in _tensorflow_version(line)
     39 
     40              Your notebook should be updated to use Tensorflow 2.
---> 41              See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2."""
     42                        ))
     43 

ValueError: Tensorflow 1 is unsupported in Colab.

Your notebook should be updated to use Tensorflow 2.
See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2.

**コメント**

よろしくお願いします。

**Comment by karaage0703** [comment]
コメントありがとうございます。また確認して修正したいと思います。

取り急ぎですが、`%tensorflow_version 1.x`の代わりに以下のコマンドで動くかもしれません（まだ試せていないです）。

```
!pip install tensorflow==1.15.2
```

GPUを使っているなら以下の方が速そうです。

```
!pip install tensorflow-gpu==1.15
```

https://stackoverflow.com/questions/73215696/did-colab-suspend-tensorflow-1-x

**Comment by karaage0703** [comment]
@zugink 
`%tensorflow_version 1.x'の代わりに`!pip install tensorflow-gpu==1.15.2`を使うことで動作確認できました。

Google Colabのノートブックも修正いたしました。Colabのノートブックのメニューの「ランタイム -> ランタイムのタイプを変更」でハードウェア アクセラレターがGPUになっていることを確認ください。

https://colab.research.google.com/drive/1dtBgF774jFSc405ik4C1Em0KM8IYUvTX?usp=sharing

貴重なフィードバックありがとうございました。

**Comment by karaage0703** [comment]
解決したと思いますので、issue closeしたいと思います。

もしまた疑問や問題ありましたら再オープンください。
