### ISSUE TITLE
「GANのモデルの学習」でのライブラリのインポートエラー

### ISSUE THREAD

**Issue by fu11ji26** [karaage0703/karaage-ai-book#37]
**ページ数**

P.201

**内容**
tensorflowのバージョン変更のエラーは
%tensorflow_version 1.x
から
!pip install tensorflow-gpu==1.15.2
に変更して解消できましたが、その次のライブラリのインポートでエラーになりました

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-12-f781bf1ab174>](https://localhost:8080/#) in <module>
----> 1 from keras.models import Sequential
      2 from keras.layers import Dense
      3 from keras.layers import Reshape
      4 from keras.layers.core import Activation
      5 from keras.layers.normalization import BatchNormalization

3 frames
[/usr/local/lib/python3.7/dist-packages/keras/backend.py](https://localhost:8080/#) in <module>
     37 from tensorflow.core.protobuf import config_pb2
     38 from tensorflow.python.eager import context
---> 39 from tensorflow.python.eager.context import get_config
     40 from tensorflow.python.framework import config
     41 from keras import backend_config

ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/eager/context.py)

**コメント**

**Comment by karaage0703** [comment]
@fu11ji26 
貴重なフィードバックありがとうございます。

```
%tensorflow_version 1.x
```

を以下の通り置き換えることで正しく動作すること確認できました。

```
!pip install tensorflow-gpu==1.15.2
!pip install keras==2.3.1
```

書籍で少しだけ触れていますが、このコードは単体のKerasを使用するため、Google Colabの仕様変更に対応するため、特定のバージョンを指定してKerasをインストールする必要がありました。

**Comment by karaage0703** [comment]
issue closeしたいと思います。
もし問題ありましたら再オープンください。

**Comment by fu11ji26** [comment]
無事実行できました。ありがとうございます！
