### ISSUE TITLE
P.75: colab_camera.use_cam() で DeprecationWarning が繰り返し出力される

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#4]
**ページ数**

P.75 の 1 行目

**内容**

誤：img_str = encimg.tostring()
正：img_str = encimg.tobytes()

colab_camera.use_cam() 実行時に次のメッセージが繰り返し出力される。
`/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:32: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.`

**コメント**

メッセージを読めば自明な修正ですが、一応報告させて頂きます。

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。感謝です。

@KazumaAndoh さん
以前は出ていなかったので、ライブラリのアップデートによる影響のようです。動作自体は問題ありませんが、ワーニングが出続けて見づらいのと、将来的に動かなくなる可能性もあるので、修正した方がベターかと思います。
P.246とP255にも同様の箇所があります。ノートブックの方は修正しました。

バージョンアップによるものなので、誤記とは少し違いますが、正誤表に追加でよいでしょうか？分けて管理した方がよいでしょうか？

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
