### ISSUE TITLE
AIモデルの性能を上げる方法：Efficientnetモデル学習時のエラー

### ISSUE THREAD

**Issue by Yogurt-neesan** [karaage0703/karaage-ai-book#42]
**ページ数**
02_karaage_ai_book_image_classification_performance.ipynb
AIモデルの性能を上げる方法：Efficientnet

**内容**
モデル学習時にエラーが生じます。
 KeyError: 'The optimizer cannot recognize variable dense_8/kernel:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.Adam.'
と表示されます

**コメント**
アップロードされているGoogle Colabを上から順に実行してみましたが、同じエラーになります。
どうぞよろしくお願いいたします。

**Comment by karaage0703** [comment]
@Yogurt-neesan 
フィードバックありがとうございます。修正しました。

https://github.com/karaage0703/karaage-ai-book/blob/master/ch02/02_karaage_ai_book_image_classification_performance.ipynb

**Comment by Yogurt-neesan** [comment]
ありがとうございました！
