### ISSUE TITLE
P123:vocabが使えないエラー

### ISSUE THREAD

**Issue by Yogurt-neesan** [karaage0703/karaage-ai-book#43]
**ページ数**

p123

**内容**

for word in model.wv.vocab.keys()のところで、
vocab.keys()はもう使えない旨のエラーがでました。
for word in model.wv.index_to_keysに変更したら動きました。

**コメント**
index_to_keysが合っているのかもよくわからないので検証のほどよろしくお願いいたします。

**Comment by karaage0703** [comment]
ありがとうございます。index_to_keysでOKです。

また、その前のコードも  `size`を`vector_size`に動かさないと動かなくなっていたので修正しました。

```python
model = word2vec.Word2Vec(
    sentences,
    sg=1,
    vector_size=300,
    window=5,
    min_count=5,
)
```

**Comment by karaage0703** [comment]
一旦closeします。問題ありましたらreopenください。
