### ISSUE TITLE
04_karaage_ai_book_gan_trainer.ipynb でのIndexErrorの解消方法を知りたいです。

### ISSUE THREAD

**Issue by Tamm2** [karaage0703/karaage-ai-book#44]
**ページ数**

ex: P.10 真ん中あたり

**内容**

ex:  xxxが分かりません・xxxについて教えてください

**コメント**

その他何かあれば（なければ空欄でOKです）

**Comment by Tamm2** [comment]
ページ数

Githubの04_karaage_ai_book_gan_trainer.ipynb

内容

上から6段目のコードを実行するとエラーが出てしまいました。
エラー内容は、
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-8-af828b82df64>](https://localhost:8080/#) in <cell line: 40>()
     57         # ノイズ付加
     58   trans_img.append(addGaussianNoise(img_src))
---> 59   trans_img.append(addSaltPepperNoise(img_src))
     60 
     61         # 反転

[<ipython-input-6-7cf8d37ba2b8>](https://localhost:8080/#) in addSaltPepperNoise(src)
     33     coords = [np.random.randint(0, i-1 , int(num_salt))
     34                  for i in src.shape]
---> 35     out[coords[:-1]] = (255,255,255)
     36 
     37     # Pepper mode

IndexError: index 257 is out of bounds for axis 0 with size 240



で、配列の要素数より大きいインデックスが使われているとのことでした。


コメント
エラーの修正方法をご教授していただけると幸いです。

**Comment by karaage0703** [comment]
@Tamm2 
回答遅くなり申し訳ありません。`trans_img.append(addSaltPepperNoise(img_src))`を削除して、少しパターンを減らせばOKです。

ただ、その先のGANの学習が、Google Colabの仕様変更によりできなくなってしまいました。
修正試みたのですが、なかなか安定した学習が難しい状況です。すぐの対応ができず申し訳ありません。

**Comment by karaage0703** [comment]
TensorFlowからPyTorchに変えて、プログラムを作り直しました。以下ノートブックを参照ください。
書籍の流れは踏襲していますが、書籍と異なる箇所があることはご容赦ください。

https://github.com/karaage0703/karaage-ai-book/blob/master/ch04/04_karaage_ai_book_gan_trainer_pytorch.ipynb

**Comment by karaage0703** [comment]
動くようになったので、クローズします。

もし何かあれば再びオープンしてください。
