### ISSUE TITLE
'DirectoryIterator' object has no attribute 'next'とエラー表示

### ISSUE THREAD

**Issue by circussacas** [karaage0703/karaage-ai-book#46]
P53

ページ最上部

最上部のコードを入力・実行すると、表記のようなエラーとなります。
実際の入力コードは次です。
(image_data, label_data) = train_data.next()
サポートサイトのコードを試してみても同じ結果です。
 オブジェクトに 'next' 属性がないということですが、どうすればよいか分かりません。

お忙しいところすみませんが、ご指導をよろしくお願いいたします。

**Comment by karaage0703** [comment]
@circussacas 
バージョンアップの関係で`train_data.__next__()`に変更になっていました。変更してお試しください。
サポートサイトのNotebookも更新しました。

**Comment by karaage0703** [comment]
解決したと思うので、クローズとさせてください。
何かあればまたオープンしてください。
