### ISSUE TITLE
文字の重複？

### ISSUE THREAD

**Issue by koichirokato** [karaage0703/karaage-ai-book#5]
**ページ数**

P.34 きゅうり農家の画像の上  

**内容**

「AI」という文字が重複している
以下、本文  

AIを用いて、きゅうりの～作業を、AIにより実現しています。  

**コメント**

個人的に気になったのですが、意図的でしたらすみません m(__)m

**Comment by karaage0703** [comment]
@koichirokato さん
貴重なご意見、ありがとうございます。確かに「AIを用いて、きゅうりの等級（ランク）を選別する作業を、AIにより実現しています。」より「AIを用いて、きゅうりの等級（ランク）を選別する作業を実現しています。」の方が自然ですね。

@KazumaAndoh さん
意味は通じますが、直した方が自然かと思います。正誤表への追記はいかがいたしましょうか？

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
