### ISSUE TITLE
P.97: load_model() の引数がソースと紙面で異なる

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#6]
**ページ数**

P.97 の 1 行目

**内容**

誤：keras_model = tf.keras.models.load_model("efficientnet_model.h5")
正：
  import tensorflow_hub as hub
  keras_model = tf.keras.models.load_model("efficientnet_model.h5", custom_objects={'KerasLayer':hub.KerasLayer})

- 引数 custom_objects が無いと次のエラーが出力される。
`ValueError: Unknown layer: KerasLayer`

- "import tensorflow_hub as hub" が無いと次のエラーが出力される。（新規ノートに書いた場合）
`NameError: name 'hub' is not defined`

**コメント**

GitHub のソースを使う前提のようですので、”import tensorflow_hub as hub" は、冗長であれば外してください。

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。

@KazumaAndoh さん
指摘の通り、紙面とコードで食い違っておりました。指摘の通りですので、正誤表に追加で良いでしょうか？

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
