### ISSUE TITLE
P.96: コピーするモデルファイル名がソースと紙面で異なる

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#7]
**ページ数**

P.96 の「AIモデルとラベルの読み込み」の前

**内容**

誤：!cp '/content/drive/My Drive/my_model.h5' './my_model.h5'
正：!cp '/content/drive/My Drive/my_model_aug.h5' './my_model_aug.h5'

**コメント**

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。

@KazumaAndoh さん
ファイル名「my_model_aug」とするとP.95で記載しているので、こちらも指摘の通り正誤表に追加するのが良いと思います。

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
