### ISSUE TITLE
P.100: Grad-CAM を使ったノートブックが見つからない

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#8]
**ページ数**

P.100 の 3 段落目

**内容**

ノートブック「02_karaage_ai_book_image_classification_grad_cam.ipynb」が、「ch2」フォルダー内に見当たりません。
ご確認をお願いします。

**コメント**

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。まだアップロードできておりませんでした。

[ch02](https://github.com/karaage0703/karaage-ai-book/tree/master/ch02)を参照ください。

**Comment by renkin3q** [comment]
当該のノートブックを確認できました。ご対応ありがとうございます！
