### ISSUE TITLE
P.100: サボートサイト→サポートサイト

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#9]
**ページ数**

P.100 の 3 段落目

**内容**

誤：サボートサイト
正：サポートサイト

**コメント**

**Comment by karaage0703** [comment]
@renkin3q さん
ご指摘ありがとうございます。

@KazumaAndoh さん
明らかな誤記なので、正誤表追記するのが良いかと思います。

**Comment by karaage0703** [comment]
[正誤表](https://github.com/karaage0703/karaage-ai-book/blob/master/ERRATA.md)に追記しましたのでcloseします。
